#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=65
USE_PROCD=1

_log() {
	logger -p daemon.info -t prometheus-node-exporter "$@"
}

start_service() {        
    echo start

    procd_open_instance

    procd_set_param command /bin/node_exporter
    procd_append_param command --web.listen-address=:9101
    
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn

    procd_close_instance
    
}                 
 
